### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by lcox2** [zroberts/walmart#1]
Trying to get your project to work in our searching function, but for some reason it doesn't want to acknowledge the existence of your methods, etc. I have followed the steps in the readme to a T. But for some reason it says your 'Resp[i]' Array isn't defined.

This is bizarre, to say the least.

**Comment by zroberts** [comment]
Can you paste in your code for the Walmart call-in?

Thanks
~Zak

**Comment by lcox2** [comment]
var walmartObject = {
        searchTerm: request.body.name,
        minPrice: '0',
        maxPrice: '10000000'
    }
    walmart.search(walmartObject, function(err, res){
        
    });
});
---
I pushed it back to before I made the commits, considering they didn't work. I just need to know what goes below. Request.body.name is where we take the name from the request that is sent. That part works, it takes the search, there is just no response.

**Comment by zroberts** [comment]
walmart.search(walmartObject, function(err, res){
        
console.log(res);
  });

Try that, should return an array of objects.

From there you'll have to loop through that array and manipulate the response on your end.

**Comment by lcox2** [comment]
Gotcha

**Comment by lcox2** [comment]
And to reply to your questions about our Repo. I am concerned as to why its not working. But I think its a consistancy issue. Something about the Master Branch not being up to date with the testing branch. Thats what Aaron explained it as

I told John to approve the Merge request, but for some reason he hasn't.

**Comment by lcox2** [comment]
And it keeps sending undefined to the console. When I log the response, its undefined.

**Comment by zroberts** [comment]
Have you tried 
If(err){
Console.log(err);
}

To see if you are getting any error instead of the response?

**Comment by lcox2** [comment]
I get an error saying "cannot log error of undefined"

**Comment by zroberts** [comment]
Post in your code again please

**Comment by zroberts** [comment]
I updated the readme with a full example, see if that helps clear things up, it's at the bottom, let me know if you're still having issues.

Thanks
~Zak

**Comment by lcox2** [comment]
Its all good Zach

Yours is working fine, but matts is having some issues with dotnev. Or at least I am.

Did you get ours to work, or are you still having issues?

**Comment by zroberts** [comment]
I haven't been able to get yours to work. 

Matt changed it so you don't need the dotenv, he must not have updated the readme.
just pass the ebay api key as the first parameter in the ebay call, like this.

ebay(ebayKey,queryObject.searchTerm, ebayMaxPrice, function(err, res){ 
if(err){
   console.log(err);
else{
   console.log(res);
  }
}
